name: Go Build
on: [ push, pull_request ]
permissions:
  checks: write

jobs:
  test:
    uses: Siroshun09/gh-actions-workflows/.github/workflows/go-test.yml@v1
    with:
      upload-results: true
      enable-cache: false
